---
- hosts: saltmasters
  remote_user: root

  vars_prompt:
    - name: "tenant_id"
      prompt: "Openstack tenant_id for salt-cloud:"
    - name: "user_id"
      prompt: "Openstack user_id for salt-cloud:" 
    - name: "api_key"
      prompt: "Openstack api_key for salt-cloud:"
    - name:  "salt_network"
      prompt: "Openstack private network uuid for salt:"

  tasks:
    - name: Remove RAX default PasswordAuthentication
      replace:
        dest: /etc/ssh/sshd_config
        regexp: ".*PasswordAuthentication yes$"

    - name: Disable Password Authentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        line: "PasswordAuthentication no"
      notify:
      - restart sshd

    - name: Add Salt Stack repository
      apt_repository:
        repo: "deb http://debian.saltstack.com/debian jessie-saltstack main"
        state: present

    - name: Add Salt Stack signing key
      apt_key:
        url: "http://debian.saltstack.com/debian-salt-team-joehealy.gpg.key"
        state: present

    - name: Install Salt Minion and Master
      apt:
        name: "{{ item }}"
        state: installed
        update_cache: yes
      with_items:
        - salt-master
        - salt-minion
        - salt-cloud

    - name: Configure Salt Master
      replace:
        dest: /etc/salt/master
        regexp: "^#interface: 0.0.0.0$"
        replace: "interface: {{ansible_eth2.ipv4.address }}"

    - name: Configure Salt Minion
      replace:
        dest: /etc/salt/minion
        regexp: "^master:.*$"
        replace: "master: {{ saltmaster }}"

    - name: Salt-Cloud Providers Config
      template:
        src: rackspace.conf.j2
        dest: /etc/salt/cloud.providers.d/rackspace.conf  

    - name: Salt-Cloud Profiles Config
      template:
        src: rackspace_profiles.conf.j2
        dest: /etc/salt/cloud.profiles.d/rackspace.conf

    - name: Start/Enable Salt Minion
      service:
        name: salt-minion
        enabled: yes
        state: started

    - name: Start/Enable Salt Master
      service: 
        name: salt-master
        enabled: yes
        state: started

  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted
